### ISSUE TITLE
docs(condicionais): Adicionar explicação de condicionais

### ISSUE THREAD

**Issue by gabicavalcante** [I-am-Gabi/minicurso-intro-python#2]
- Adicionar section de explicação

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue title must have one of the following prefixes: "feat(*): ", "fix(*): ", "docs(*): ", "refactor(*): ", "algo(*): " [(?)](https://gitmagic.io/rules/#/issue/subject-must-include-prefix)

[Click here](https://app.gitmagic.io/I-am-Gabi/minicurso-intro-python/2/8219a6c2-d5b8-4016-827d-cdfa17622bc5/bbfbc2e8-3625-42a2-a535-1862cd92b899) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue title must have one of the following prefixes: "feat(*): ", "fix(*): ", "docs(*): ", "refactor(*): ", "algo(*): " [(?)](https://gitmagic.io/rules/#/issue/subject-must-include-prefix)

[Click here](https://app.gitmagic.io/I-am-Gabi/minicurso-intro-python/2/8219a6c2-d5b8-4016-827d-cdfa17622bc5/bbfbc2e8-3625-42a2-a535-1862cd92b899) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
