### ISSUE TITLE
algo(repeticoes): Adicionar algoritmo de repetições 

### ISSUE THREAD

**Issue by gabicavalcante** [I-am-Gabi/minicurso-intro-python#3]
- Adicionar no exemplo as repetições 
  https://gabrielacavalcante.gitbooks.io/python/content/repeticoes.html

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue title must start with uppercase [(?)](https://gitmagic.io/rules/#/issue/subject-must-start-with-case)

[Click here](https://app.gitmagic.io/I-am-Gabi/minicurso-intro-python/3/8219a6c2-d5b8-4016-827d-cdfa17622bc5/e9e7dae4-4b75-4856-bb6e-b92922803d80) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
